### ISSUE TITLE
script error

### ISSUE THREAD

**Issue by sysdl132** [YunoHost-Apps/gitlab_ynh#107]
```
2020-04-18 09:14:27,729: INFO - Installing the app 'gitlab'…
2020-04-18 09:14:28,071: DEBUG - The permission database has been resynchronized
2020-04-18 09:14:28,506: DEBUG - status file not found for 'gitlab'
Traceback (most recent call last):
  File "/usr/lib/moulinette/yunohost/app.py", line 2235, in _get_app_status
    with open(app_setting_path + '/status.json') as f:
IOError: [Errno 2] No such file or directory: u'/etc/yunohost/apps/gitlab/status.json'
2020-04-18 09:14:28,523: DEBUG - cannot get app setting 'update_time' for 'gitlab' ('update_time')
2020-04-18 09:14:28,600: DEBUG - SSOwat configuration generated
2020-04-18 09:14:28,642: DEBUG - No default hook for action 'post_app_addaccess' in /usr/share/yunohost/hooks/
2020-04-18 09:14:28,647: DEBUG - No custom hook for action 'post_app_addaccess' in /etc/yunohost/hooks.d/
2020-04-18 09:14:28,649: DEBUG - Permission 'gitlab.main' created
2020-04-18 09:14:28,650: DEBUG - Full log of this operation: '<a href="#/tools/logs/20200418-011428-permission_create-gitlab" style="text-decoration:underline">Create permission 'gitlab'</a>'
2020-04-18 09:14:28,682: DEBUG - Executing command 'sh -c YNH_APP_INSTANCE_NUMBER=1 YNH_CWD=/var/cache/yunohost/from_file/gitlab_ynh-7c352aff3fb13fc425d76716477c28db5d54ac99/scripts YNH_APP_INSTANCE_NAME=gitlab YNH_APP_ARG_USE_WEB_ACCOUNT=1 YNH_STDINFO=/tmp/tmps3iZwO/stdinfo YNH_APP_ARG_IS_PUBLIC=1 YNH_APP_ARG_ADMIN=sysdl132 YNH_INTERFACE=api YNH_APP_ID=gitlab YNH_APP_ARG_PATH=/git YNH_STDRETURN=/tmp/tmpfA9tL1/stdreturn YNH_APP_ARG_DOMAIN=sysdl132.nohost.me BASH_XTRACEFD=7 /bin/bash -x "./install" sysdl132.nohost.me /git sysdl132 1 1 gitlab 7>&1'…
2020-04-18 09:14:28,689: DEBUG - About to run the command '['sh', '-c', 'YNH_APP_INSTANCE_NUMBER=1 YNH_CWD=/var/cache/yunohost/from_file/gitlab_ynh-7c352aff3fb13fc425d76716477c28db5d54ac99/scripts YNH_APP_INSTANCE_NAME=gitlab YNH_APP_ARG_USE_WEB_ACCOUNT=1 YNH_STDINFO=/tmp/tmps3iZwO/stdinfo YNH_APP_ARG_IS_PUBLIC=1 YNH_APP_ARG_ADMIN=sysdl132 YNH_INTERFACE=api YNH_APP_ID=gitlab YNH_APP_ARG_PATH=/git YNH_STDRETURN=/tmp/tmpfA9tL1/stdreturn YNH_APP_ARG_DOMAIN=sysdl132.nohost.me BASH_XTRACEFD=7 /bin/bash -x "./install" sysdl132.nohost.me /git sysdl132 1 1 gitlab 7>&1']'
2020-04-18 09:14:28,837: DEBUG - + source _common.sh
2020-04-18 09:14:28,839: DEBUG - ++ pkg_dependencies='openssh-server bc'
2020-04-18 09:14:28,839: DEBUG - + source /usr/share/yunohost/helpers
2020-04-18 09:14:28,840: DEBUG - +++ run-parts --list /usr/share/yunohost/helpers.d
2020-04-18 09:14:28,846: DEBUG - ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
2020-04-18 09:14:28,846: DEBUG - ++ '[' -r /usr/share/yunohost/helpers.d/apt ']'
2020-04-18 09:14:28,847: DEBUG - ++ . /usr/share/yunohost/helpers.d/apt
2020-04-18 09:14:28,847: DEBUG - ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
2020-04-18 09:14:28,848: DEBUG - ++ '[' -r /usr/share/yunohost/helpers.d/backup ']'
2020-04-18 09:14:28,848: DEBUG - ++ . /usr/share/yunohost/helpers.d/backup
2020-04-18 09:14:28,852: DEBUG - +++ CAN_BIND=1
2020-04-18 09:14:28,853: DEBUG - ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
2020-04-18 09:14:28,854: DEBUG - ++ '[' -r /usr/share/yunohost/helpers.d/fail2ban ']'
2020-04-18 09:14:28,855: DEBUG - ++ . /usr/share/yunohost/helpers.d/fail2ban
2020-04-18 09:14:28,855: DEBUG - ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
2020-04-18 09:14:28,961: DEBUG - ++ '[' -r /usr/share/yunohost/helpers.d/getopts ']'
2020-04-18 09:14:28,969: DEBUG - ++ . /usr/share/yunohost/helpers.d/getopts
2020-04-18 09:14:28,970: DEBUG - ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
2020-04-18 09:14:28,970: DEBUG - ++ '[' -r /usr/share/yunohost/helpers.d/logging ']'
2020-04-18 09:14:28,971: DEBUG - ++ . /usr/share/yunohost/helpers.d/logging
2020-04-18 09:14:28,972: DEBUG - +++ increment_progression=0
2020-04-18 09:14:28,987: DEBUG - +++ previous_weight=0
2020-04-18 09:14:28,988: DEBUG - +++ max_progression=-1
2020-04-18 09:14:28,989: DEBUG - +++ progress_scale=20
2020-04-18 09:14:28,989: DEBUG - +++ progress_string2='####################'
2020-04-18 09:14:28,990: DEBUG - +++ progress_string1=++++++++++++++++++++
2020-04-18 09:14:28,991: DEBUG - +++ progress_string0=....................
2020-04-18 09:14:28,992: DEBUG - ++++ date +%s
2020-04-18 09:14:29,009: DEBUG - +++ base_time=1587172468
2020-04-18 09:14:29,022: DEBUG - ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
2020-04-18 09:14:29,023: DEBUG - ++ '[' -r /usr/share/yunohost/helpers.d/logrotate ']'
2020-04-18 09:14:29,023: DEBUG - ++ . /usr/share/yunohost/helpers.d/logrotate
2020-04-18 09:14:29,024: DEBUG - ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
2020-04-18 09:14:29,034: DEBUG - ++ '[' -r /usr/share/yunohost/helpers.d/mysql ']'
2020-04-18 09:14:29,035: DEBUG - ++ . /usr/share/yunohost/helpers.d/mysql
2020-04-18 09:14:29,037: DEBUG - +++ MYSQL_ROOT_PWD_FILE=/etc/yunohost/mysql
2020-04-18 09:14:29,038: DEBUG - ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
2020-04-18 09:14:29,039: DEBUG - ++ '[' -r /usr/share/yunohost/helpers.d/network ']'
2020-04-18 09:14:29,039: DEBUG - ++ . /usr/share/yunohost/helpers.d/network
2020-04-18 09:14:29,048: DEBUG - ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
2020-04-18 09:14:29,049: DEBUG - ++ '[' -r /usr/share/yunohost/helpers.d/nginx ']'
2020-04-18 09:14:29,050: DEBUG - ++ . /usr/share/yunohost/helpers.d/nginx
2020-04-18 09:14:29,050: DEBUG - ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
2020-04-18 09:14:29,051: DEBUG - ++ '[' -r /usr/share/yunohost/helpers.d/nodejs ']'
2020-04-18 09:14:29,052: DEBUG - ++ . /usr/share/yunohost/helpers.d/nodejs
2020-04-18 09:14:29,052: DEBUG - +++ n_install_dir=/opt/node_n
2020-04-18 09:14:29,057: DEBUG - +++ node_version_path=/opt/node_n/n/versions/node
2020-04-18 09:14:29,058: DEBUG - +++ export N_PREFIX=/opt/node_n
2020-04-18 09:14:29,059: DEBUG - +++ N_PREFIX=/opt/node_n
2020-04-18 09:14:29,059: DEBUG - ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
2020-04-18 09:14:29,066: DEBUG - ++ '[' -r /usr/share/yunohost/helpers.d/php ']'
2020-04-18 09:14:29,066: DEBUG - ++ . /usr/share/yunohost/helpers.d/php
2020-04-18 09:14:29,067: DEBUG - ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
2020-04-18 09:14:29,068: DEBUG - ++ '[' -r /usr/share/yunohost/helpers.d/postgresql ']'
2020-04-18 09:14:29,073: DEBUG - ++ . /usr/share/yunohost/helpers.d/postgresql
2020-04-18 09:14:29,074: DEBUG - +++ PSQL_ROOT_PWD_FILE=/etc/yunohost/psql
2020-04-18 09:14:29,074: DEBUG - ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
2020-04-18 09:14:29,075: DEBUG - ++ '[' -r /usr/share/yunohost/helpers.d/setting ']'
2020-04-18 09:14:29,082: DEBUG - ++ . /usr/share/yunohost/helpers.d/setting
2020-04-18 09:14:29,184: DEBUG - ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
2020-04-18 09:14:29,186: DEBUG - ++ '[' -r /usr/share/yunohost/helpers.d/string ']'
2020-04-18 09:14:29,187: DEBUG - ++ . /usr/share/yunohost/helpers.d/string
2020-04-18 09:14:29,189: DEBUG - ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
2020-04-18 09:14:29,190: DEBUG - ++ '[' -r /usr/share/yunohost/helpers.d/systemd ']'
2020-04-18 09:14:29,190: DEBUG - ++ . /usr/share/yunohost/helpers.d/systemd
2020-04-18 09:14:29,191: DEBUG - ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
2020-04-18 09:14:29,192: DEBUG - ++ '[' -r /usr/share/yunohost/helpers.d/user ']'
2020-04-18 09:14:29,198: DEBUG - ++ . /usr/share/yunohost/helpers.d/user
2020-04-18 09:14:29,199: DEBUG - ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
2020-04-18 09:14:29,200: DEBUG - ++ '[' -r /usr/share/yunohost/helpers.d/utils ']'
2020-04-18 09:14:29,209: DEBUG - ++ . /usr/share/yunohost/helpers.d/utils
2020-04-18 09:14:29,210: DEBUG - + ynh_abort_if_errors
2020-04-18 09:14:29,211: DEBUG - + set -eu
2020-04-18 09:14:29,217: DEBUG - + trap ynh_exit_properly EXIT
2020-04-18 09:14:29,218: DEBUG - + domain=sysdl132.nohost.me
2020-04-18 09:14:29,219: DEBUG - + path_url=/git
2020-04-18 09:14:29,220: DEBUG - + is_public=1
2020-04-18 09:14:29,225: DEBUG - + use_web_account=1
2020-04-18 09:14:29,227: DEBUG - + admin=sysdl132
2020-04-18 09:14:29,228: DEBUG - + app=gitlab
2020-04-18 09:14:29,231: DEBUG - + ynh_script_progression '--message=Validating installation parameters...' --weight=1
2020-04-18 09:14:29,231: DEBUG - + set +x
2020-04-18 09:14:29,338: DEBUG - + set +x
2020-04-18 09:14:29,339: DEBUG - + echo '! Helper used in legacy mode !'
2020-04-18 09:14:29,339: DEBUG - + set +x
2020-04-18 09:14:29,340: DEBUG - + echo '[....................] > Validating installation parameters...'
2020-04-18 09:14:29,341: DEBUG - + set -x
2020-04-18 09:14:29,342: DEBUG - + config_path=/etc/gitlab
2020-04-18 09:14:29,342: DEBUG - + final_path=/opt/gitlab
2020-04-18 09:14:29,350: DEBUG - + test '!' -e /opt/gitlab
2020-04-18 09:14:29,350: DEBUG - ++ grep 64
2020-04-18 09:14:29,372: DEBUG - ++ uname -m
2020-04-18 09:14:29,375: DEBUG - + '[' -n '' ']'
2020-04-18 09:14:29,382: DEBUG - ++ grep 86
2020-04-18 09:14:29,383: DEBUG - ++ uname -m
2020-04-18 09:14:29,383: DEBUG - + '[' -n i686 ']'
2020-04-18 09:14:29,384: DEBUG - + ynh_die 'Gitlab is not compatible with x86 architecture'
2020-04-18 09:14:29,390: DEBUG - + local legacy_args=mc
2020-04-18 09:14:29,391: DEBUG - + args_array=([m]=message= [c]=ret_code=)
2020-04-18 09:14:29,392: DEBUG - + declare -Ar args_array
2020-04-18 09:14:29,395: DEBUG - + local message
2020-04-18 09:14:29,398: INFO - [....................] > Validating installation parameters...
2020-04-18 09:14:29,407: DEBUG - + local ret_code
2020-04-18 09:14:29,408: DEBUG - + ynh_handle_getopts_args 'Gitlab is not compatible with x86 architecture'
2020-04-18 09:14:29,411: DEBUG - + set +x
2020-04-18 09:14:29,513: DEBUG - + echo '! Helper used in legacy mode !'
2020-04-18 09:14:29,514: WARNING - Gitlab is not compatible with x86 architecture
2020-04-18 09:14:29,518: DEBUG - + set +x
2020-04-18 09:14:29,519: DEBUG - + echo 'Gitlab is not compatible with x86 architecture'
2020-04-18 09:14:29,519: DEBUG - + exit 1
2020-04-18 09:14:29,521: DEBUG - + ynh_exit_properly
2020-04-18 09:14:29,522: DEBUG - + local exit_code=1
2020-04-18 09:14:29,523: DEBUG - + '[' 1 -eq 0 ']'
2020-04-18 09:14:29,523: DEBUG - + trap '' EXIT
2020-04-18 09:14:29,525: DEBUG - + set +eu
2020-04-18 09:14:29,525: DEBUG - + sleep 0.5
2020-04-18 09:14:29,930: DEBUG - + type -t ynh_clean_setup
2020-04-18 09:14:29,931: DEBUG - + ynh_clean_setup
2020-04-18 09:14:29,932: DEBUG - + ynh_exec_warn_less ynh_secure_remove --file=
2020-04-18 09:14:29,932: DEBUG - + eval ynh_secure_remove --file=
2020-04-18 09:14:29,933: DEBUG - ++ ynh_secure_remove --file=
2020-04-18 09:14:29,933: DEBUG - ++ local legacy_args=f
2020-04-18 09:14:29,934: DEBUG - ++ args_array=([f]=file=)
2020-04-18 09:14:29,934: DEBUG - ++ declare -Ar args_array
2020-04-18 09:14:29,935: DEBUG - ++ local file
2020-04-18 09:14:29,935: DEBUG - ++ ynh_handle_getopts_args --file=
2020-04-18 09:14:29,936: DEBUG - ++ set +x
2020-04-18 09:14:30,041: DEBUG - ++ local 'forbidden_path=     /var/www     /home/yunohost.app'
2020-04-18 09:14:30,041: WARNING - 
2020-04-18 09:14:30,046: DEBUG - ++ '[' 1 -ge 2 ']'
2020-04-18 09:14:30,048: DEBUG - ++ [[ -z '' ]]
2020-04-18 09:14:30,050: DEBUG - ++ ynh_print_warn '--message=ynh_secure_remove called with empty argument, ignoring.'
2020-04-18 09:14:30,051: DEBUG - ++ local legacy_args=m
2020-04-18 09:14:30,053: DEBUG - ++ args_array=([m]=message=)
2020-04-18 09:14:30,056: DEBUG - ++ declare -Ar args_array
2020-04-18 09:14:30,058: DEBUG - ++ local message
2020-04-18 09:14:30,059: DEBUG - ++ ynh_handle_getopts_args '--message=ynh_secure_remove called with empty argument, ignoring.'
2020-04-18 09:14:30,061: DEBUG - ++ set +x
2020-04-18 09:14:30,062: DEBUG - ++ ynh_print_log '\e[93m\e[1m[WARN]\e[0m ynh_secure_remove called with empty argument, ignoring.'
2020-04-18 09:14:30,064: DEBUG - ++ echo -e '\e[93m\e[1m[WARN]\e[0m ynh_secure_remove called with empty argument, ignoring.'
2020-04-18 09:14:30,069: DEBUG - [93m[1m[WARN][0m ynh_secure_remove called with empty argument, ignoring.
2020-04-18 09:14:30,070: DEBUG - + ynh_clean_check_starting
2020-04-18 09:14:30,074: DEBUG - + '[' -n '' ']'
2020-04-18 09:14:30,076: DEBUG - + '[' -n '' ']'
2020-04-18 09:14:30,078: DEBUG - + ynh_die
2020-04-18 09:14:30,079: DEBUG - + local legacy_args=mc
2020-04-18 09:14:30,080: DEBUG - + args_array=([m]=message= [c]=ret_code=)
2020-04-18 09:14:30,081: DEBUG - + declare -Ar args_array
2020-04-18 09:14:30,081: DEBUG - + local message
2020-04-18 09:14:30,082: DEBUG - + local ret_code
2020-04-18 09:14:30,083: DEBUG - + ynh_handle_getopts_args
2020-04-18 09:14:30,083: DEBUG - + set +x
2020-04-18 09:14:30,084: DEBUG - + echo ''
2020-04-18 09:14:30,085: DEBUG - + exit 1
2020-04-18 09:14:30,218: ERROR - Could not install gitlab: An error occurred inside the app installation script
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 301, in wrapper
    curr_v = params[k]
KeyError: 'label'
```

**Comment by sysdl132** [comment]
what should I fill here?(domain or IP)
![image](https://user-images.githubusercontent.com/54708046/79626228-0a218080-8161-11ea-982a-df29f4b6437f.png)

**Comment by sysdl132** [comment]
I know why.The server isn't compatible i386.I will try amd64 later.
