### ISSUE TITLE
Upgrade failed

### ISSUE THREAD

**Issue by rodinux** [YunoHost-Apps/gitlab_ynh#227]
### Describe the bug

**

### Context

- Hardware: *VPS bought online *
- YunoHost version: *11.2.3*
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- upgrading, current package version: *15.11.2~ynh1*

### Steps to reproduce

    ```sh
    sudo yunohost app upgrade gitlab
    ```

### Expected behavior

*Upgrade gitlab to version 16.2.4~ynh1 with no errors*

### Logs

```
Info: Now upgrading gitlab...
Info: [++..................] > Backing up the app before upgrading (may take a while)...
Info: [##+.................] > Installing dependencies...
Info: [###++++++++++.......] > Setting up source files...
Info: Wait for the migration in the background to finish

Warning: File /etc/gitlab/gitlab.rb has been manually modified since the installation or last upgrade. So it has been duplicated in /var/cache/yunohost/appconfbackup//etc/gitlab/gitlab.rb.backup.20230817.132821
Warning: --- /var/cache/yunohost/appconfbackup//etc/gitlab/gitlab.rb.backup.20230817.132821     2023-05-31 08:46:50.370695114 +0200
Warning: +++ /etc/gitlab/gitlab.rb      2023-08-17 13:28:21.603107330 +0200
Warning: @@ -3343,3 +3343,5 @@
Warning:  # spamcheck['classifier']['log_directory'] = "/var/log/gitlab/spam-classifier"
Warning:  from_file '/etc/gitlab/gitlab-persistent.rb'
Warning: +# Last chance to fix Gitlab
Warning: +package['modify_kernel_parameters'] = false
Warning: [Error] Upgrade failed.

Warning: 961297 (this may take some time)
Warning: The app was restored to the way it was before the failed upgrade.
Error: Could not upgrade gitlab: An error occurred inside the app upgrade script
Info: The operation 'Upgrade the 'gitlab' app' could not be completed. Please share the full log of this operation using the command 'yunohost log share 20230817-110810-app_upgrade-gitlab' to get help
Error: Could not upgrade gitlab: Something unexpected went wrong:
  File "/usr/lib/python3/dist-packages/yunohost/hook.py", line 538, in hook_exec_with_script_debug_if_failure
    operation_logger.dump_script_log_extract_for_debugging()
  File "/usr/lib/python3/dist-packages/yunohost/log.py", line 749, in dump_script_log_extract_for_debugging
    lines = [line.strip().split(": ", 1)[1] for line in lines]
  File "/usr/lib/python3/dist-packages/yunohost/log.py", line 749, in <listcomp>
    lines = [line.strip().split(": ", 1)[1] for line in lines]
IndexError: list index out of range
```

**Comment by alexAubin** [comment]
... Please share the ***full*** log ...

**Comment by rodinux** [comment]
I can give you a link to upload a file because the log is too long ! I can't put it on a paste !
https://nuage.numericloud.eu/s/F4YnfZF97kNgdpk

**Comment by rodinux** [comment]
Or also I can name it in .md to see the share ?? (now the file is in .log)

**Comment by orhtej2** [comment]
Error:

```
2023-08-17 13:27:09,351: DEBUG - Recipe: gitlab::database_migrations
2023-08-17 13:27:09,351: DEBUG -   * ruby_block[check remote PG version] action nothing (skipped due to action :nothing)
2023-08-17 13:27:09,354: DEBUG -   * rails_migration[gitlab-rails] action run
2023-08-17 13:27:09,392: DEBUG -     * bash_hide_env[migrate gitlab-rails database] action run
2023-08-17 13:27:09,393: DEBUG -       [execute] bash: BASH_XTRACEFD: 7: invalid value for trace file descriptor
2023-08-17 13:28:16,389: DEBUG -                 Running db:migrate rake task
2023-08-17 13:28:16,390: DEBUG -                 main: == [advisory_lock_connection] object_id: 224400, pg_backend_pid: 1717946
2023-08-17 13:28:16,390: DEBUG -                 main: == 20211202041233 InitSchema: migrating =======================================
2023-08-17 13:28:16,917: DEBUG -                 main: -- execute(" FULL DB SCHEMA HERE SNIPPED ")rake aborted!
2023-08-17 13:28:17,210: DEBUG -                 StandardError: An error has occurred, this and all later migrations canceled:
2023-08-17 13:28:17,210: DEBUG - 
2023-08-17 13:28:17,210: DEBUG -                 PG::DuplicateSchema: ERROR:  schema "gitlab_partitions_dynamic" already exists
2023-08-17 13:28:17,210: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/db/migrate/20211202041233_init_schema.rb:7:in `up'
2023-08-17 13:28:17,211: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/connection_proxy.rb:121:in `public_send'
2023-08-17 13:28:17,211: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/connection_proxy.rb:121:in `block in write_using_load_balancer'
2023-08-17 13:28:17,211: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/load_balancer.rb:127:in `block in read_write'
2023-08-17 13:28:17,211: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/load_balancer.rb:198:in `retry_with_backoff'
2023-08-17 13:28:17,212: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/load_balancer.rb:116:in `read_write'
2023-08-17 13:28:17,212: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/connection_proxy.rb:120:in `write_using_load_balancer'
2023-08-17 13:28:17,212: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/connection_proxy.rb:72:in `transaction'
2023-08-17 13:28:17,213: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database.rb:369:in `block in transaction'
2023-08-17 13:28:17,213: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database.rb:368:in `transaction'
2023-08-17 13:28:17,213: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/migrations/lock_retry_mixin.rb:36:in `ddl_transaction'
2023-08-17 13:28:17,213: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/migrations/pg_backend_pid.rb:15:in `block in with_advisory_lock_connection'
2023-08-17 13:28:17,214: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/migrations/pg_backend_pid.rb:12:in `with_advisory_lock_connection'
2023-08-17 13:28:17,214: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/db.rake:117:in `configure_database'
2023-08-17 13:28:17,214: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/db.rake:95:in `block (3 levels) in <top (required)>'
2023-08-17 13:28:17,215: DEBUG -                 /opt/gitlab/embedded/bin/bundle:23:in `load'
2023-08-17 13:28:17,215: DEBUG -                 /opt/gitlab/embedded/bin/bundle:23:in `<main>'
2023-08-17 13:28:17,215: DEBUG - 
2023-08-17 13:28:17,216: DEBUG -                 Caused by:
2023-08-17 13:28:17,216: DEBUG -                 ActiveRecord::StatementInvalid: PG::DuplicateSchema: ERROR:  schema "gitlab_partitions_dynamic" already exists
2023-08-17 13:28:17,216: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/db/migrate/20211202041233_init_schema.rb:7:in `up'
2023-08-17 13:28:17,217: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/connection_proxy.rb:121:in `public_send'
2023-08-17 13:28:17,217: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/connection_proxy.rb:121:in `block in write_using_load_balancer'
2023-08-17 13:28:17,217: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/load_balancer.rb:127:in `block in read_write'
2023-08-17 13:28:17,217: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/load_balancer.rb:198:in `retry_with_backoff'
2023-08-17 13:28:17,218: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/load_balancer.rb:116:in `read_write'
2023-08-17 13:28:17,218: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/connection_proxy.rb:120:in `write_using_load_balancer'
2023-08-17 13:28:17,218: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/connection_proxy.rb:72:in `transaction'
2023-08-17 13:28:17,219: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database.rb:369:in `block in transaction'
2023-08-17 13:28:17,219: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database.rb:368:in `transaction'
2023-08-17 13:28:17,219: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/migrations/lock_retry_mixin.rb:36:in `ddl_transaction'
2023-08-17 13:28:17,219: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/migrations/pg_backend_pid.rb:15:in `block in with_advisory_lock_connection'
2023-08-17 13:28:17,220: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/migrations/pg_backend_pid.rb:12:in `with_advisory_lock_connection'
2023-08-17 13:28:17,220: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/db.rake:117:in `configure_database'
2023-08-17 13:28:17,220: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/db.rake:95:in `block (3 levels) in <top (required)>'
2023-08-17 13:28:17,221: DEBUG -                 /opt/gitlab/embedded/bin/bundle:23:in `load'
2023-08-17 13:28:17,221: DEBUG -                 /opt/gitlab/embedded/bin/bundle:23:in `<main>'
2023-08-17 13:28:17,221: DEBUG - 
2023-08-17 13:28:17,222: DEBUG -                 Caused by:
2023-08-17 13:28:17,222: DEBUG -                 PG::DuplicateSchema: ERROR:  schema "gitlab_partitions_dynamic" already exists
2023-08-17 13:28:17,222: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/db/migrate/20211202041233_init_schema.rb:7:in `up'
2023-08-17 13:28:17,223: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/connection_proxy.rb:121:in `public_send'
2023-08-17 13:28:17,224: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/connection_proxy.rb:121:in `block in write_using_load_balancer'
2023-08-17 13:28:17,224: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/load_balancer.rb:127:in `block in read_write'
2023-08-17 13:28:17,225: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/load_balancer.rb:198:in `retry_with_backoff'
2023-08-17 13:28:17,225: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/load_balancer.rb:116:in `read_write'
2023-08-17 13:28:17,225: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/connection_proxy.rb:120:in `write_using_load_balancer'
2023-08-17 13:28:17,226: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/connection_proxy.rb:72:in `transaction'
2023-08-17 13:28:17,226: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database.rb:369:in `block in transaction'
2023-08-17 13:28:17,226: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database.rb:368:in `transaction'
2023-08-17 13:28:17,228: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/migrations/lock_retry_mixin.rb:36:in `ddl_transaction'
2023-08-17 13:28:17,228: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/migrations/pg_backend_pid.rb:15:in `block in with_advisory_lock_connection'
2023-08-17 13:28:17,228: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/migrations/pg_backend_pid.rb:12:in `with_advisory_lock_connection'
2023-08-17 13:28:17,228: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/db.rake:117:in `configure_database'
2023-08-17 13:28:17,229: DEBUG -                 /opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/db.rake:95:in `block (3 levels) in <top (required)>'
2023-08-17 13:28:17,229: DEBUG -                 /opt/gitlab/embedded/bin/bundle:23:in `load'
2023-08-17 13:28:17,229: DEBUG -                 /opt/gitlab/embedded/bin/bundle:23:in `<main>'
2023-08-17 13:28:17,229: DEBUG -                 Tasks: TOP => db:migrate
2023-08-17 13:28:17,249: DEBUG -                 (See full trace by running task with --trace)
2023-08-17 13:28:17,306: DEBUG - 
2023-08-17 13:28:17,307: DEBUG - 
2023-08-17 13:28:17,395: DEBUG -       ================================================================================
2023-08-17 13:28:17,448: DEBUG -       Error executing action `run` on resource 'bash_hide_env[migrate gitlab-rails database]'
2023-08-17 13:28:17,449: DEBUG -       ================================================================================
```

**Comment by rodinux** [comment]
> Error (full DB schema snipped as it didn't fit in comment):

I haven't this message in my logs... not sure understand what's going wrong...

**Comment by orhtej2** [comment]
> I haven't this message in my logs... not sure understand what's going wrong...

Literally search the timestamps, these lines were taken from the file you linked before.

**Comment by rodinux** [comment]
> > I haven't this message in my logs... not sure understand what's going wrong...
> 
> Literally search the timestamps, these lines were taken from the file you linked before.

Ok I see line 20387 `2023-08-17 13:28:17,222: DEBUG -                 PG::DuplicateSchema: ERROR:  schema "gitlab_partitions_dynamic" already exists`

So, what means this error ?? 

`PG::DuplicateSchema: ERROR:  schema "gitlab_partitions_dynamic" already exists` 
I see a lot of issues with this message in the gitlab forum...

**Comment by orhtej2** [comment]
The statement before attempted to create full schema rather than perform update for some reason I think. No clue what's causing it.

**Comment by kay0u** [comment]
Can you please try to upgrade to the testing version please?

```
sudo yunohost app upgrade gitlab -u https://github.com/YunoHost-Apps/gitlab_ynh/tree/testing
```

(You don't have to do anything after that to revert to the stable version when a new version becomes available).
